defmodule Cwallet.Mnemonic do
  @moduledoc """
  Module for generating a mnemonic phrase using BIP-39 standards
  """

  @doc """
  Generates a phrase from a given list of rows
  generated by the GenerateIndexes module, where each index
  represents a row from the wordlist.txt file
  ## Examples
      iex> Mnemonic.generate_phrase([2047, 33, 47])
      "zoo aerobic album"
  """
  @spec generate_phrase(list()) :: String.t()
  def generate_phrase(rows) do
    for row <- rows do
      elem(get_wordlist(), row) <> " "
    end
    |> List.to_string()
    |> String.trim()
  end

  @doc """
  Finds the directory priv in :cwallet project
  and reads the file wordslist.txt
  returns a tuple with all the words
  """
  @spec get_wordlist() :: tuple()
  def get_wordlist do
    {:ok, word_list} =
      :cwallet
      |> :code.priv_dir()
      |> Path.join("wordlist.txt")
      |> File.read()

    word_list
    |> String.split("\n")
    |> List.to_tuple()
  end
end
